Storev2Firearms = [
  [
    //Rifles
    [
      "arifle_SPAR_01_blk_F",
      "arifle_SPAR_01_GL_blk_F",
      "arifle_SPAR_02_blk_F",
      "arifle_SPAR_03_blk_F",
      "srifle_LRR_tna_F",
      "arifle_SDAR_F",
      "SMG_05_F"
    ],
    //Ammo
    [
      "20Rnd_762x51_Mag",
      "7Rnd_408_Mag",
      "20Rnd_556x45_UW_mag",
      "30Rnd_556x45_Stanag",
      "150Rnd_556x45_Drum_Mag_F",
      "30Rnd_9x21_Mag_SMG_02"
    ],
    //Scopes
    [
      "optic_ERCO_blk_F",
      "optic_Holosight_blk_F",
      "optic_Hamr",
      "optic_LRPS_tna_F"
    ],
    //Rails
    [
      "acc_pointer_IR",
      "acc_flashlight",
      "bipod_01_F_blk"
    ],
    //Muzzles
    [
      "muzzle_snds_m",
      "muzzle_snds_m_khk_F",
      "muzzle_snds_m_snd_F",
      "muzzle_snds_b",
      "muzzle_snds_B_khk_F",
      "muzzle_snds_B_snd_F"
    ]
  ],
  [
    //Sidearms
    [
      "hgun_P07_khk_F",
      "hgun_Pistol_heavy_01_F",
      "hgun_Rook40_F"
    ],
    //Ammo
    [
      "11Rnd_45ACP_Mag",
      "16Rnd_9x21_Mag"
    ]
  ],
  [
    //Gear
    //Launchers
    [
      "launch_NLAW_F"
    ],
    [
      "NLAW_F"
    ],
    //Nades
    [
      "SmokeShell",
      "SmokeShellRed",
      "SmokeShellBlue",
      "SmokeShellGreen",
      "SmokeShellOrange",
      "SmokeShellPurple",
      "SmokeShellYellow",
      "MiniGrenade",
      "HandGrenade",
      "B_IR_Grenade"
    ],
    [
      "Rangefinder",
      "Binocular",
      "Laserdesignator_01_khk_F",
      "NVGoggles_INDEP"
    ],
    [
      "FirstAidKit",
      "ItemMap",
      "ItemCompass",
      "ItemWatch",
      "ItemRadio",
      "ItemGPS"
    ]
  ]
];
Storev2Clothing = [
  [
    //All
    [
      //Clothing
      "U_B_T_Soldier_F",
      "U_B_T_Soldier_AR_F",
      "U_B_T_FullGhillie_tna_F",
      "U_B_Wetsuit",
      "U_B_CTRG_Soldier_2_F",
      "U_B_CTRG_Soldier_3_F",
      "U_B_HeliPilotCoveralls",
      "U_B_PilotCoveralls"
    ],
    [
      //Vest
      "V_Rangemaster_belt",
      "V_TacChestrig_grn_F",
      "V_RebreatherB",
      "V_PlateCarrierL_CTRG",
      "V_PlateCarrierH_CTRG",
      "V_PlateCarrier2_tna_F",
      "V_TacVest_blk"
    ],
    [
      //Backpacks
      "B_AssaultPack_blk",
      "B_TacticalPack_blk",
      "B_Carryall_oli"
    ],
    [
      //headgear
      "H_Booniehat_tna_F",
      "H_Watchcap_khk",
      "H_HelmetB_light_black",
      "H_MilCap_tna_F",
      "H_Beret_02",
      "H_CrewHelmetHeli_B",
      "H_PilotHelmetFighter_B"
    ],
    [
    //Eyewear
      "G_Shades_Black",
      "G_Balaclava_TI_blk_F",
      "G_B_Diving",
      "G_Bandanna_oli",
      "G_Aviator"
    ]
  ],
  []
];
